allStages <- function(vv){
  fsize <- 10
  tit <- vv[, paste0('icd ',unique(icd),
                     ', sex: ', unique(sex),
                     ', agr: ', unique(agr))]
  p <- ggplot2::ggplot(data=vv, ggplot2::aes(x=years, y=surv)) +
    ggplot2::geom_line(ggplot2::aes(linetype=status,),colour='black', size = 1.4) +# geom_point(colour=black, size = 1.5) +
    ggplot2::ylab('relative survival [%]') +
    ggplot2::xlab('follow-up year') +
    ggplot2::facet_wrap(~ stage)
  p <- p+ggplot2::guides(linetype=ggplot2::guide_legend(title="",keywidth = 2,# keyheight = 1,
                                                        override.aes = list(size=1.0)))
  p <- p +ggplot2::theme(legend.position = "bottom")
  p <- p +ggplot2::theme(#legend.title = "survival",
    legend.position = "bottom",
    legend.text=ggplot2::element_text(size=fsize-1),
    axis.title = ggplot2::element_text(size=fsize,face="bold"),
    axis.text = ggplot2::element_text(size=fsize,colour="black"))
  p <- p + ggplot2::ggtitle(tit) +
    ggplot2::theme(title =ggplot2::element_text(size=10, face='bold'))
  return(p)
}
myTitle = function(xx){
  tit <- icd_agr_sex(xx)
  if(xx$Param$runTime$CondRelSurv_ne_Pop==0)
    tit <- paste(tit,'\n','Conditional 1-year relative survival',
                 'in [95% - 103%] in all follow-up years:\n',
                 'No classification of missed deaths')
  if(xx$Param$runTime$rs_0Increase==0 &
     xx$Param$runTime$CondRelSurv_ne_Pop != 0)
    tit <- paste(tit,'\n','Relative Survival in original data did not increase at follow-up end.\n',
         'Classification of missed deaths is not carried out.')
}
oneStage <- function(xx,vv){
  fsize <- 10
#  tit <- myTitle(xx)
  tit <- icd_agr_sex(xx)
  if(xx$Param$runTime$CondRelSurv_ne_Pop==0)
    tit  <- paste(tit,'(no classification)')
  p <- ggplot2::ggplot(data=vv, ggplot2::aes(x=years, y=surv)) +
  ggplot2::geom_line(ggplot2::aes(linetype=status,),colour='black',linewidth = 1.4) +# geom_point(colour=black, size = 1.5) +
  ggplot2::ylab('relative survival [%]') +
  ggplot2::xlab('follow-up year')
  ggplot2::ggtitle(tit)
  p <- p+ggplot2::guides(linetype=ggplot2::guide_legend(title='',keywidth = 2,# keyheight = 1,
                                                        override.aes = list(size=1.0)))
  p <- p +ggplot2::theme(legend.position = "bottom")
  p <- p +ggplot2::theme(#legend.title = "survival",
    legend.position = "bottom",
    legend.text=ggplot2::element_text(size=fsize-1),
    axis.title = ggplot2::element_text(size=fsize,face="bold"),
    axis.text = ggplot2::element_text(size=fsize,colour="black"))
  p <- p + ggplot2::ggtitle(tit) +
    ggplot2::theme(title =ggplot2::element_text(size=fsize-2, face='bold'))
  return(p)
}


#'\code{classify.plotSurv} plots relative survival
#' rates by follow-up time before and after
#'exclusion of missed deaths by \code{classify}
#'
#' \code{plotSurv} plots relative survival by follow-up
#'  time before and after exclusion of cases classified
#'  as 'missed' deaths in \code{classify}.
#'  Relative survival rates > 200\% are truncated.
#'
#' @param xx object  of type \code{list} generated by classify.
#'
#' @return ggplot object
#' @export
#'
#' @examples
#' data(C61)
#' data(sp)
#' xx = classify(C61,sp,survYears = 30,fu_end=2016,md_cutoff = 4.0)
#' classify.plotSurv(xx)
#'
#'@seealso
#'  \code{\link{classify}}
#'  \code{\link{classify.parameter}}
#'  \code{\link{classify.regCoef}}
#'  \code{\link{classify.summary}}
#'
classify.plotSurv <- function(xx){#Stage='Missing'
  noClassiMessage(xx)
  nofu_increaseMessage(xx)
  uu <- data.table(xx$survTab)
  uu[,rs_0 := as.numeric(rs_before)]
  uu[,rs_0 := ifelse(rs_0 > 200,NA,rs_0)]
  uu[,rs_1 := as.numeric(rs_after)]
  uu[,rs_1 := ifelse(rs_1 > 200,NA,rs_1)]
  uu <- uu[,.(icd,sex,agr,years,stage,rs_1,rs_0)]
  vv <- melt(uu, id.vars = c('icd','sex','agr','stage',"years"),
             measure.vars = c("rs_0", "rs_1"))
  levels(vv$variable)=c('before classification','after classification')
  names(vv) <- c("icd","sex","agr",'stage','years','status','surv')
  pp <- oneStage(xx,vv)
  return(pp)
}
