#' \code{classify.regCoef} shows coefficients and p-values of the logistic
#' regression used for the  classification
#' in \code{classify}
#'
#' @param xx object of type \code{list} generated by classify.
#'
#' @return data.frame with regression coefficients
#' @export
#'
#' @examples
#' data(C61)
#' data(sp)
#' xx = classify(C61,sp,survYears = 30,fu_end=2016,md_cutoff = 4.0)
#' classify.regCoef(xx)
#'
#'@seealso
#'  \code{\link{classify}}
#'  \code{\link{classify.parameter}}
#'  \code{\link{classify.plotSurv}}
#'  \code{\link{classify.summary}}

classify.regCoef = function(xx){
  noClassiMessage(xx)
  nofu_increaseMessage(xx)
  cls = c("varnames","Estimate","Std. Error","Pr(>|z|)")
  aa <- list(
    Stratum = icd_agr_sex(xx),
    'Logistic Regression' = xx$regCoef[,(cls),with=F]
  )
  return(aa)
}
