noClassiMessage = function(xx){
  mm = c('Conditional 1-year relative survival was in \n [95% - 103%]',
    ' in all follow-up years.\n',
    'Classification of missed deaths was not carried out.')
  if(xx$Param$runTime$CondRelSurv_ne_Pop==0)
    message(mm)
}
nofu_increaseMessage = function(xx){
  mm = c('Relative survival in original data did \n not increase at follow-up end.\n',
  'Classification of missed deaths was not carried out.')
  if(xx$Param$runTime$rs_0Increase==0 &
     xx$Param$runTime$CondRelSurv_ne_Pop != 0)
      message(mm)
}
icd_agr_sex <- function(xx){
  dat = data.table(xx$dat)
  icd = paste(dat[,sort(unique(icd))],collapse = ' ')
  sex <- paste(dat[,sort(unique(sex))],collapse = ' ')
  agr  <- paste(dat[,sort(unique(agr))],collapse = ' ')
  stage  <- paste(dat[,sort(unique(stage))],collapse = ' ')
  paste0('icd: ',icd,', sex: ',sex,', agr: ',agr,', stage: ',stage)
}
#'Summary of missed deaths classification
#'
#'\code{classify.summary()} calculates the number of patients,
#' survivors, deaths and missed deaths detected by
#'  \code{classify}
#' In addition, the percentage of classified missed
#'  deaths relative to the number of deaths is provided
#'
#'
#' @param xx object  of type \code{list} generated by \code{classify()}.
#'
#' @return list object with the described values
#'
#' @export
#'
#' @examples
#' data(C61)
#' data(sp)
#' xx = classify(C61,sp,survYears = 30,fu_end=2016,md_cutoff = 4.0)
#' classify.Summary(xx)
#'
#'@seealso
#'  \code{\link{classify}}
#'  \code{\link{classify.parameter}}
#'  \code{\link{classify.plotSurv}}
#'  \code{\link{classify.regCoef}}
#'
classify.summary = function(xx){#dp=xx
#  xPrint <- function(x, dec = 1) sprintf(paste("%.", dec, "f", sep = ""), x)
  noClassiMessage(xx)
  nofu_increaseMessage(xx)
  dd <- setDT(xx$dat);
  uu <- dd[,.(patients= .N),by=stage]
  uu <- merge(uu,dd[death==0,.(survivals= .N),by=stage],by='stage',all.x=T)
  uu <- merge(uu,dd[death==1,.(deaths= .N),by=stage],by='stage',all.x=T)
  uu <- merge(uu,dd[missedDeath==1,.(missedDeaths = .N),by=stage],by='stage',all.x=T)
  uu[,missedDeaths := ifelse(is.na(missedDeaths),0,missedDeaths)]
  # bb <- data.frame(t(apply(uu[,-1],2,sum,na.rm=T)))
  # bb$stage <- 'total'
  # bb <- setDT(rbind(uu,bb))
  uu[,md_percent := ifelse(deaths > 0,	xPrint(missedDeaths*100/(deaths),2),0)]
  aa <- uu[,.(patients,
               survivals,deaths,
               missedDeaths,md_percent)]
  setnames(aa,'missedDeaths','missed deaths[N]')
  setnames(aa,'md_percent','missed deaths[%]')
  uuu = list(Stratum = icd_agr_sex(xx),
             Summary = aa)
#  print(uuu$statistic)
  return(uuu)
}
