algoName = function(xx){
  if(xx$Param$runTime$rs_0Increase==0)
    return('No search')
  if(xx$Param$runTime$scoring==1)
    return('scoring')
  return('logistic regression')
}
relSurvIncreaseName = function(xx){
  if(xx$Param$runTime$rs_0Increase[1]==0)
    return('Did not increase at follow-up end')
  return('Increased at follow-up end')
}

#' \code{classify.parameter} shows parameters used for
#' missed deaths classification in \code{classify}
#'
#' @param xx object  of type \code{list} generated by classify.
#'
#' @return data.frame with parameters of the
#' missed deaths classification by \code{classify()}
#' @export
#'
#' @examples
#' data(C61)
#' data(sp)
#' xx = classify(C61,sp,survYears = 30,fu_end=2016,md_cutoff = 4.0)
#' classify.Param(xx)
#'
#'@seealso
#'  \code{\link{classify}}
#'  \code{\link{classify.plotSurv}}
#'  \code{\link{classify.regCoef}}
#'  \code{\link{classify.summary}}

classify.parameter <- function(xx){#xx = rr
  noClassiMessage(xx)
  nofu_increaseMessage(xx)
  opt <- xx$Param$opt
  getArgu <- function(opt){
    list(survYears = paste('Maximal follow-up time:',opt$survYears,'years'),
         fu_end = paste0('Follow-up end: ',opt$lastYear,'-Dec-31 ','(fu_end = ',opt$lastYear,')'),
         periodWidth = paste0('Width of the analysis period for relative survival estimation: ',
                              opt$periodWidth,' years',
                              ' (period window: ',opt$perbeg,'-Jan-01 : ',opt$lastYear,'-Dec-31)' ),
         md_cutoff = paste0('Maximum accepted percentage of classified missed deaths: ',opt$md_cutoff,'%')
    )
  }
  aa <- list(
    Stratum = icd_agr_sex(xx),
    Argument = getArgu(opt)
  )

  thresholdNames = function(runTime){ # runtime = xx$Param$runTime
    paste(runTime$ageCut,'years age at follow-up end and',
          runTime$survCut,'years follow-up time')
  }
  rr = list(
       'Relative Survival in original data' = relSurvIncreaseName(xx),
       'Algorithm for classifying missed deaths'= algoName(xx))
  if(xx$Param$runTime$rs_0Increase==1)
       rr$'threshold for classifying missed deaths:' = thresholdNames(xx$Param$runTime
  )
  # uu[,md_gt_cutoff := ifelse(md_gt_cutoff==1,'yes','no')]
  # uu = uu[,.(stage,reg_sig,p_reg_md,md_gt_cutoff,ageCut,survCut,quant)]
  if(xx$Param$runTime$CondRelSurv_ne_Pop==1)
    print(c(aa,rr))
  if(xx$Param$runTime$CondRelSurv_ne_Pop==0){
    print(aa)
  }
}
